### ISSUE TITLE
Docs provider roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/opencodegraph#11]
The docs provider is on the `docs-provider` branch for now.

- [ ] simplify cache interface
- [ ] deal with different content types (markdown/html) differently
- [ ] make it slurp up gdocs/confluence/markdown in repos
- [ ] show OCG annotations (but in a way that doesn't overlay lines in the file, is more passive?)
- [ ] show a demo of Cody working with this
- [ ] show docs most relevant to the current visible portion or the selection, not the whole file

**Comment by sqs** [comment]
Update from https://twitter.com/sqs/status/1741385389628354881

The WIP documentation context provider for OpenCodeGraph is much better now at chunking and relevance. Still working on the UX...thinking it should be a UI list per-file, with maybe a small indicator at the top of file.

Uses embeddings search and TF-IDF, point it at a URL containing docs pages for it to crawl. Support for more kinds of docs such as gdocs, wikis, etc., will be there eventually.

(Branch `docs-provider` in the opencodegraph repo.)
